site_name: Tracking AI Course
site_description: "A course to help you understand how to track the exponential growth of AI systems capabilities and their impact on society.  An analysis of the limitations of LLMs and the need for world models"
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/tracking-ai-course/'
repo_url: 'https://github.com/dmccreary/tracking-ai-course'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About This Course: about.md
  - Course Description: course-description.md
  - Chapters:
    - Introduction: chapters/index.md
    - Current State: chapters/current-state.md
    - Benchmarking AI: chapters/benchmarking-ai.md
    - MMLU: chapters/mmlu/index.md
    - LM Arena: chapters/lm-arena/index.md
    - Objective LLMs for The Classroom: chapters/objective-llm-quality.md
    - AGI Predicted Dates: chapters/agi-predicted-dates.md
    - The LLMs Only Path: chapters/skepticism-of-the-llm-only-path.md
  - Stories:
    - Intro: stories/index.md
    - AI Winters: stories/ai-winters/index.md
    - Yann LeCun: stories/yann-lecun/index.md
  - MicroSims:
    - Intro: sims/index.md
    - Four AI Futures: sims/four-futures/index.md
    - Moore's Law: sims/moores-law/index.md
    - Power Wall: sims/power-wall/index.md
    - AI Pace Accelerating: sims/ai-pace-accelerating/index.md
    - AI Benchmarks Timeline: sims/ai-benchmarks-timeline/index.md
    - MMLU Timeline: sims/mmlu-timeline/index.md
    - LM Arena Timeline: sims/lm-arena-timeline/index.md
    - Learning Graph: sims/learning-graph/index.md
    - Autoregressive: sims/autoregressive/index.md
    - AI Timeline: sims/timeline/index.md
    - Tokenizer: sims/tokenizer/index.md
    - MicroSim Templates: sims/templates/index.md
  - Prompts:
    - Intro: prompts/index.md
    - Concept Enumeration: prompts/03-concept-enumeration.md
    - Concept Dependency: prompts/04-concept-dependencies.md
    - Concept Taxonomy: prompts/05-taxonomy-concept.md
    - Glossary: prompts/06-glossary.md
  - Checklist: checklist.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Feedback: feedback.md
  - License: license.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
  # enable LaTeX equation rendering
  - pymdownx.arithmatex:
      generic: true
extra_css:
   - css/extra.css
extra_javascript:
   - js/extra.js
   - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra:
  analytics:
    provider: google
    property: G-KTYGHZCPM3