site_name: Tracking AI Course
site_description: "A course to help you understand how to track the exponential growth of AI systems capabilities and their impact on society.  An analysis of the limitations of LLMs and the need for world models"
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/tracking-ai-course/'
repo_url: 'https://github.com/dmccreary/tracking-ai-course'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About This Course: about.md
  - Course Description: course-description.md
  - Chapters:
    - Introduction: chapters/index.md
    - What is AI?: chapters/what-is-ai.md
    - Current State: chapters/current-state.md
    - Benchmarking AI: chapters/benchmarking-ai.md
    - AI vs. Humans: chapters/ai-vs-humans.md
    - Long Task Rate: chapters/long-tasks/index.md
    - Intelligence vs Price: chapters/intelligence-vs-price.md
    - MMLU: chapters/mmlu/index.md
    - LM Arena: chapters/lm-arena/index.md
    - HealthBench: chapters/healthbench/index.md
    - Objective LLMs for The Classroom: chapters/objective-llm-quality.md
    - AGI Predicted Dates: chapters/agi-predicted-dates.md
    - AI Investments: chapters/ai-investments/index.md
    - Number of Models: chapters/number-of-models.md
    - Model Parameter Count: chapters/model-parameter-count/index.md
    - More Data: chapters/more-data.md
    - The LLMs Only Path: chapters/skepticism-of-the-llm-only-path.md
    - Porter's Five Forces Model: chapters/porters-five-forces/index.md
    - AI Hype Cycle: chapters/ai-hype-cycles.md
    - Stationary vs. Non-Stationary Policies: chapters/stationary-vs-non-stationary-policies.md
    - Curriculum Learning: chapters/curriculum-learning.md

  - Stories:
    - Intro: stories/index.md
    - AI Winters: stories/ai-winters/index.md
    - Alexnet: stories/alexnet/index.md
    - Yann LeCun: stories/yann-lecun/index.md
    - The Jellyfish and the Flatworm: stories/jellyfish-and-flatworm/index.md
  
  - MicroSims:
    - Intro: sims/index.md
    - Four AI Futures: sims/four-futures/index.md
    - Moore's Law: sims/moores-law/index.md
    - Power Wall: sims/power-wall/index.md
    - AI Pace Accelerating: sims/ai-pace-accelerating/index.md
    - AI Benchmarks Timeline: sims/ai-benchmarks-timeline/index.md
    - MMLU Timeline: sims/mmlu-timeline/index.md
    - LM Arena Timeline: sims/lm-arena-timeline/index.md
    - Learning Graph: sims/learning-graph/index.md
    - Book Generation Workflow: sims/book-gen-workflow/index.md
    - Book Levels: sims/book-levels/index.md
    - Bloom's Taxonomy: sims/blooms-taxonomy/index.md
    - Technology Adoption Curve: sims/technology-adoption/index.md
    - Porter's Five Forces: sims/porters-five-forces/index.md
    - The AI Flywheel: sims/ai-flywheel/index.md
    - AI Causes: sims/ai-causes/index.md
    - AI SWOT Analysis: sims/swot/index.md
    - Technology Hype Cycle: sims/hype-cycle/index.md
    - AI Capability Maturity Model: sims/ai-cmm/index.md
    - Autoregressive: sims/autoregressive/index.md
    - AI Timeline: sims/timeline/index.md
    - Tokenizer: sims/tokenizer/index.md
    - MicroSim Templates: sims/templates/index.md
  - Prompts:
    - Intro: prompts/index.md
    - Concept Enumeration: prompts/03-concept-enumeration.md
    - Concept Dependency: prompts/04-concept-dependencies.md
    - Concept Taxonomy: prompts/05-taxonomy-concept.md
    - Glossary: prompts/06-glossary.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Feedback: feedback.md
  - License: license.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
  - social_override
markdown_extensions:
  - meta
  - admonition
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  # enable LaTeX equation rendering
  - pymdownx.arithmatex:
      generic: true
extra_css:
   - css/extra.css
extra_javascript:
   - js/extra.js
   - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra:
  analytics:
    provider: google
    property: G-KTYGHZCPM3